services:
  prometheus-1:
    image: prom/prometheus:latest
    container_name: prometheus-1
    volumes:
      - ./prometheus-1/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ./prometheus-1/data/:/prometheus/:Z
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9090/-/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 9091:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/
    networks:
      - prometheus
  prometheus-2:
    image: prom/prometheus:latest
    container_name: prometheus-2
    volumes:
      - ./prometheus-2/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ./prometheus-2/data/:/prometheus/:Z
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9090/-/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 9092:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/
    networks:
      - prometheus
  prometheus-3:
    image: prom/prometheus:latest
    container_name: prometheus-3
    volumes:
      - ./prometheus-3/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ./prometheus-3/data/:/prometheus/:Z
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9090/-/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 9093:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/
    networks:
      - prometheus
networks:
  prometheus:
    driver: bridge